In [20]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

In [21]:
url = 'https://fbref.com/en/comps/Big5/Big-5-European-Leagues-Stats'

response = requests.get(url)
soup = BeautifulSoup(response.text)
big_five_league = soup.select('table.stats_table')[0]
links = big_five_league.find_all('a')

In [22]:
links = [l.get('href') for l in links]
links = [l for l in links if '/squads/' in l]
links = ['https://fbref.com' + l for l in links]
links

['https://fbref.com/en/squads/c7a9f859/2023-2024/Bayer-Leverkusen-Stats',
 'https://fbref.com/en/squads/53a2f082/2023-2024/Real-Madrid-Stats',
 'https://fbref.com/en/squads/d609edc0/2023-2024/Internazionale-Stats',
 'https://fbref.com/en/squads/b8fd03ef/2023-2024/Manchester-City-Stats',
 'https://fbref.com/en/squads/18bb7c10/2023-2024/Arsenal-Stats',
 'https://fbref.com/en/squads/e2d8892c/2023-2024/Paris-Saint-Germain-Stats',
 'https://fbref.com/en/squads/206d90db/2023-2024/Barcelona-Stats',
 'https://fbref.com/en/squads/822bd0ba/2023-2024/Liverpool-Stats',
 'https://fbref.com/en/squads/598bc722/2023-2024/Stuttgart-Stats',
 'https://fbref.com/en/squads/9024a00a/2023-2024/Girona-Stats',
 'https://fbref.com/en/squads/054efa67/2023-2024/Bayern-Munich-Stats',
 'https://fbref.com/en/squads/db3b9613/2023-2024/Atletico-Madrid-Stats',
 'https://fbref.com/en/squads/dc56fe14/2023-2024/Milan-Stats',
 'https://fbref.com/en/squads/fd6114db/2023-2024/Monaco-Stats',
 'https://fbref.com/en/squads/acbb6a5b/2023-2024/RB-Leipzig-Stats',
 'https://fbref.com/en/squads/e0652b02/2023-2024/Juventus-Stats',
 'https://fbref.com/en/squads/add600ae/2023-2024/Dortmund-Stats',
 'https://fbref.com/en/squads/922493f3/2023-2024/Atalanta-Stats',
 'https://fbref.com/en/squads/2b390eca/2023-2024/Athletic-Club-Stats',
 'https://fbref.com/en/squads/1d8099f8/2023-2024/Bologna-Stats',
 'https://fbref.com/en/squads/fb08dbb3/2023-2024/Brest-Stats',
 'https://fbref.com/en/squads/8602292d/2023-2024/Aston-Villa-Stats',
 'https://fbref.com/en/squads/cb188c0c/2023-2024/Lille-Stats',
 'https://fbref.com/en/squads/361ca564/2023-2024/Tottenham-Hotspur-Stats',
 'https://fbref.com/en/squads/cf74a709/2023-2024/Roma-Stats',
 'https://fbref.com/en/squads/cff3d9bb/2023-2024/Chelsea-Stats',
 'https://fbref.com/en/squads/132ebc33/2023-2024/Nice-Stats',
 'https://fbref.com/en/squads/7213da33/2023-2024/Lazio-Stats',
 'https://fbref.com/en/squads/b2b47a98/2023-2024/Newcastle-United-Stats',
 'https://fbref.com/en/squads/421387cf/2023-2024/Fiorentina-Stats',
 'https://fbref.com/en/squads/e31d1cd9/2023-2024/Real-Sociedad-Stats',
 'https://fbref.com/en/squads/19538871/2023-2024/Manchester-United-Stats',
 'https://fbref.com/en/squads/d53c0b06/2023-2024/Lyon-Stats',
 'https://fbref.com/en/squads/fd4e0f7d/2023-2024/Lens-Stats',
 'https://fbref.com/en/squads/fc536746/2023-2024/Real-Betis-Stats',
 'https://fbref.com/en/squads/5725cc7b/2023-2024/Marseille-Stats',
 'https://fbref.com/en/squads/d48ad4ff/2023-2024/Napoli-Stats',
 'https://fbref.com/en/squads/2a8183b3/2023-2024/Villarreal-Stats',
 'https://fbref.com/en/squads/105360fe/2023-2024/Torino-Stats',
 'https://fbref.com/en/squads/f0ac8ee6/Eintracht-Frankfurt-Stats',
 'https://fbref.com/en/squads/7fdd64e0/2023-2024/Reims-Stats',
 'https://fbref.com/en/squads/7c21e445/2023-2024/West-Ham-United-Stats',
 'https://fbref.com/en/squads/b3072e00/2023-2024/Rennes-Stats',
 'https://fbref.com/en/squads/033ea6b8/Hoffenheim-Stats',
 'https://fbref.com/en/squads/658bf2de/2023-2024/Genoa-Stats',
 'https://fbref.com/en/squads/47c64c55/2023-2024/Crystal-Palace-Stats',
 'https://fbref.com/en/squads/dcc91a7b/2023-2024/Valencia-Stats',
 'https://fbref.com/en/squads/3f8c4b5f/2023-2024/Toulouse-Stats',
 'https://fbref.com/en/squads/d07537b9/2023-2024/Brighton-and-Hove-Albion-Stats',
 'https://fbref.com/en/squads/4ba7cbea/2023-2024/Bournemouth-Stats',
 'https://fbref.com/en/squads/18d9d2a7/2023-2024/Heidenheim-Stats',
 'https://fbref.com/en/squads/fd962109/2023-2024/Fulham-Stats',
 'https://fbref.com/en/squads/62add3bf/Werder-Bremen-Stats',
 'https://fbref.com/en/squads/a486e511/Freiburg-Stats',
 'https://fbref.com/en/squads/281b0e73/2023-2024/Montpellier-Stats',
 'https://fbref.com/en/squads/8d6fd021/2023-2024/Alaves-Stats',
 'https://fbref.com/en/squads/8cec06e1/2023-2024/Wolverhampton-Wanderers-Stats',
 'https://fbref.com/en/squads/03c57e2b/2023-2024/Osasuna-Stats',
 'https://fbref.com/en/squads/21680aa4/2023-2024/Monza-Stats',
 'https://fbref.com/en/squads/0cdc4311/Augsburg-Stats',
 'https://fbref.com/en/squads/c0d3eab4/2023-2024/Strasbourg-Stats',
 'https://fbref.com/en/squads/7848bd64/2023-2024/Getafe-Stats',
 'https://fbref.com/en/squads/d3fd31cc/2023-2024/Everton-Stats',
 'https://fbref.com/en/squads/4eaa11d7/Wolfsburg-Stats',
 'https://fbref.com/en/squads/ad2be733/2023-2024/Sevilla-Stats',
 'https://fbref.com/en/squads/f25da7fb/2023-2024/Celta-Vigo-Stats',
 'https://fbref.com/en/squads/2aa12281/2023-2024/Mallorca-Stats',
 'https://fbref.com/en/squads/0049d422/2023-2024/Las-Palmas-Stats',
 'https://fbref.com/en/squads/cd051869/2023-2024/Brentford-Stats',
 'https://fbref.com/en/squads/a224b06a/Mainz-05-Stats',
 'https://fbref.com/en/squads/32f3ee20/Monchengladbach-Stats',
 'https://fbref.com/en/squads/0e72edf2/2023-2024/Hellas-Verona-Stats',
 'https://fbref.com/en/squads/98e8af82/2023-2024/Rayo-Vallecano-Stats',
 'https://fbref.com/en/squads/ffcbe334/2023-2024/Lecce-Stats',
 'https://fbref.com/en/squads/04eea015/2023-2024/Udinese-Stats',
 'https://fbref.com/en/squads/d7a486cd/2023-2024/Nantes-Stats',
 'https://fbref.com/en/squads/7a41008f/Union-Berlin-Stats',
 'https://fbref.com/en/squads/b42c6323/Bochum-Stats',
 'https://fbref.com/en/squads/a3d88bd8/2023-2024/Empoli-Stats',
 'https://fbref.com/en/squads/c4260e09/2023-2024/Cagliari-Stats',
 'https://fbref.com/en/squads/5c2737db/2023-2024/Le-Havre-Stats',
 'https://fbref.com/en/squads/6a7ad59d/2023-2024/Frosinone-Stats',
 'https://fbref.com/en/squads/ee7c297c/2023-2024/Cadiz-Stats',
 'https://fbref.com/en/squads/f83960ae/2023-2024/Metz-Stats',
 'https://fbref.com/en/squads/d2c87802/2023-2024/Lorient-Stats',
 'https://fbref.com/en/squads/e4a775cb/2023-2024/Nottingham-Forest-Stats',
 'https://fbref.com/en/squads/e2befd26/2023-2024/Sassuolo-Stats',
 'https://fbref.com/en/squads/bc357bf7/2023-2024/Koln-Stats',
 'https://fbref.com/en/squads/d9676424/2023-2024/Clermont-Foot-Stats',
 'https://fbref.com/en/squads/e297cd13/2023-2024/Luton-Town-Stats',
 'https://fbref.com/en/squads/943e8050/2023-2024/Burnley-Stats',
 'https://fbref.com/en/squads/78ecf4bb/2023-2024/Almeria-Stats',
 'https://fbref.com/en/squads/a0435291/2023-2024/Granada-Stats',
 'https://fbref.com/en/squads/6a6967fc/2023-2024/Darmstadt-98-Stats',
 'https://fbref.com/en/squads/c5577084/2023-2024/Salernitana-Stats',
 'https://fbref.com/en/squads/1df6b87e/2023-2024/Sheffield-United-Stats']

In [23]:
links_with_2023 = [l for l in links if '2023' in l]
links_without_2023 = [l for l in links if'2023' not in l]

In [24]:
links_without_2023

['https://fbref.com/en/squads/f0ac8ee6/Eintracht-Frankfurt-Stats',
 'https://fbref.com/en/squads/033ea6b8/Hoffenheim-Stats',
 'https://fbref.com/en/squads/62add3bf/Werder-Bremen-Stats',
 'https://fbref.com/en/squads/a486e511/Freiburg-Stats',
 'https://fbref.com/en/squads/0cdc4311/Augsburg-Stats',
 'https://fbref.com/en/squads/4eaa11d7/Wolfsburg-Stats',
 'https://fbref.com/en/squads/a224b06a/Mainz-05-Stats',
 'https://fbref.com/en/squads/32f3ee20/Monchengladbach-Stats',
 'https://fbref.com/en/squads/7a41008f/Union-Berlin-Stats',
 'https://fbref.com/en/squads/b42c6323/Bochum-Stats']

In [25]:
codes_teams = {}
split_links_with_2023 = [(url.split('/')[5], url.split('/')[7]) for url in links_with_2023]

for code, team_name in split_links_with_2023:
    codes_teams[team_name] = code
    print(f"Code : {code}   Team Name : {team_name}")

Code : c7a9f859   Team Name : Bayer-Leverkusen-Stats
Code : 53a2f082   Team Name : Real-Madrid-Stats
Code : d609edc0   Team Name : Internazionale-Stats
Code : b8fd03ef   Team Name : Manchester-City-Stats
Code : 18bb7c10   Team Name : Arsenal-Stats
Code : e2d8892c   Team Name : Paris-Saint-Germain-Stats
Code : 206d90db   Team Name : Barcelona-Stats
Code : 822bd0ba   Team Name : Liverpool-Stats
Code : 598bc722   Team Name : Stuttgart-Stats
Code : 9024a00a   Team Name : Girona-Stats
Code : 054efa67   Team Name : Bayern-Munich-Stats
Code : db3b9613   Team Name : Atletico-Madrid-Stats
Code : dc56fe14   Team Name : Milan-Stats
Code : fd6114db   Team Name : Monaco-Stats
Code : acbb6a5b   Team Name : RB-Leipzig-Stats
Code : e0652b02   Team Name : Juventus-Stats
Code : add600ae   Team Name : Dortmund-Stats
Code : 922493f3   Team Name : Atalanta-Stats
Code : 2b390eca   Team Name : Athletic-Club-Stats
Code : 1d8099f8   Team Name : Bologna-Stats
Code : fb08dbb3   Team Name : Brest-Stats
Code : 8602292d   Team Name : Aston-Villa-Stats
Code : cb188c0c   Team Name : Lille-Stats
Code : 361ca564   Team Name : Tottenham-Hotspur-Stats
Code : cf74a709   Team Name : Roma-Stats
Code : cff3d9bb   Team Name : Chelsea-Stats
Code : 132ebc33   Team Name : Nice-Stats
Code : 7213da33   Team Name : Lazio-Stats
Code : b2b47a98   Team Name : Newcastle-United-Stats
Code : 421387cf   Team Name : Fiorentina-Stats
Code : e31d1cd9   Team Name : Real-Sociedad-Stats
Code : 19538871   Team Name : Manchester-United-Stats
Code : d53c0b06   Team Name : Lyon-Stats
Code : fd4e0f7d   Team Name : Lens-Stats
Code : fc536746   Team Name : Real-Betis-Stats
Code : 5725cc7b   Team Name : Marseille-Stats
Code : d48ad4ff   Team Name : Napoli-Stats
Code : 2a8183b3   Team Name : Villarreal-Stats
Code : 105360fe   Team Name : Torino-Stats
Code : 7fdd64e0   Team Name : Reims-Stats
Code : 7c21e445   Team Name : West-Ham-United-Stats
Code : b3072e00   Team Name : Rennes-Stats
Code : 658bf2de   Team Name : Genoa-Stats
Code : 47c64c55   Team Name : Crystal-Palace-Stats
Code : dcc91a7b   Team Name : Valencia-Stats
Code : 3f8c4b5f   Team Name : Toulouse-Stats
Code : d07537b9   Team Name : Brighton-and-Hove-Albion-Stats
Code : 4ba7cbea   Team Name : Bournemouth-Stats
Code : 18d9d2a7   Team Name : Heidenheim-Stats
Code : fd962109   Team Name : Fulham-Stats
Code : 281b0e73   Team Name : Montpellier-Stats
Code : 8d6fd021   Team Name : Alaves-Stats
Code : 8cec06e1   Team Name : Wolverhampton-Wanderers-Stats
Code : 03c57e2b   Team Name : Osasuna-Stats
Code : 21680aa4   Team Name : Monza-Stats
Code : c0d3eab4   Team Name : Strasbourg-Stats
Code : 7848bd64   Team Name : Getafe-Stats
Code : d3fd31cc   Team Name : Everton-Stats
Code : ad2be733   Team Name : Sevilla-Stats
Code : f25da7fb   Team Name : Celta-Vigo-Stats
Code : 2aa12281   Team Name : Mallorca-Stats
Code : 0049d422   Team Name : Las-Palmas-Stats
Code : cd051869   Team Name : Brentford-Stats
Code : 0e72edf2   Team Name : Hellas-Verona-Stats
Code : 98e8af82   Team Name : Rayo-Vallecano-Stats
Code : ffcbe334   Team Name : Lecce-Stats
Code : 04eea015   Team Name : Udinese-Stats
Code : d7a486cd   Team Name : Nantes-Stats
Code : a3d88bd8   Team Name : Empoli-Stats
Code : c4260e09   Team Name : Cagliari-Stats
Code : 5c2737db   Team Name : Le-Havre-Stats
Code : 6a7ad59d   Team Name : Frosinone-Stats
Code : ee7c297c   Team Name : Cadiz-Stats
Code : f83960ae   Team Name : Metz-Stats
Code : d2c87802   Team Name : Lorient-Stats
Code : e4a775cb   Team Name : Nottingham-Forest-Stats
Code : e2befd26   Team Name : Sassuolo-Stats
Code : bc357bf7   Team Name : Koln-Stats
Code : d9676424   Team Name : Clermont-Foot-Stats
Code : e297cd13   Team Name : Luton-Town-Stats
Code : 943e8050   Team Name : Burnley-Stats
Code : 78ecf4bb   Team Name : Almeria-Stats
Code : a0435291   Team Name : Granada-Stats
Code : 6a6967fc   Team Name : Darmstadt-98-Stats
Code : c5577084   Team Name : Salernitana-Stats
Code : 1df6b87e   Team Name : Sheffield-United-Stats

In [26]:
split_links_without_2023 = [(url.split('/')[5], url.split('/')[6]) for url in links_without_2023]

for code, team_name in split_links_without_2023:
    codes_teams[team_name] = code
    print(f"Code : {code}   Team Name : {team_name}")

Code : f0ac8ee6   Team Name : Eintracht-Frankfurt-Stats
Code : 033ea6b8   Team Name : Hoffenheim-Stats
Code : 62add3bf   Team Name : Werder-Bremen-Stats
Code : a486e511   Team Name : Freiburg-Stats
Code : 0cdc4311   Team Name : Augsburg-Stats
Code : 4eaa11d7   Team Name : Wolfsburg-Stats
Code : a224b06a   Team Name : Mainz-05-Stats
Code : 32f3ee20   Team Name : Monchengladbach-Stats
Code : 7a41008f   Team Name : Union-Berlin-Stats
Code : b42c6323   Team Name : Bochum-Stats

In [27]:
codes_teams

{'Bayer-Leverkusen-Stats': 'c7a9f859',
 'Real-Madrid-Stats': '53a2f082',
 'Internazionale-Stats': 'd609edc0',
 'Manchester-City-Stats': 'b8fd03ef',
 'Arsenal-Stats': '18bb7c10',
 'Paris-Saint-Germain-Stats': 'e2d8892c',
 'Barcelona-Stats': '206d90db',
 'Liverpool-Stats': '822bd0ba',
 'Stuttgart-Stats': '598bc722',
 'Girona-Stats': '9024a00a',
 'Bayern-Munich-Stats': '054efa67',
 'Atletico-Madrid-Stats': 'db3b9613',
 'Milan-Stats': 'dc56fe14',
 'Monaco-Stats': 'fd6114db',
 'RB-Leipzig-Stats': 'acbb6a5b',
 'Juventus-Stats': 'e0652b02',
 'Dortmund-Stats': 'add600ae',
 'Atalanta-Stats': '922493f3',
 'Athletic-Club-Stats': '2b390eca',
 'Bologna-Stats': '1d8099f8',
 'Brest-Stats': 'fb08dbb3',
 'Aston-Villa-Stats': '8602292d',
 'Lille-Stats': 'cb188c0c',
 'Tottenham-Hotspur-Stats': '361ca564',
 'Roma-Stats': 'cf74a709',
 'Chelsea-Stats': 'cff3d9bb',
 'Nice-Stats': '132ebc33',
 'Lazio-Stats': '7213da33',
 'Newcastle-United-Stats': 'b2b47a98',
 'Fiorentina-Stats': '421387cf',
 'Real-Sociedad-Stats': 'e31d1cd9',
 'Manchester-United-Stats': '19538871',
 'Lyon-Stats': 'd53c0b06',
 'Lens-Stats': 'fd4e0f7d',
 'Real-Betis-Stats': 'fc536746',
 'Marseille-Stats': '5725cc7b',
 'Napoli-Stats': 'd48ad4ff',
 'Villarreal-Stats': '2a8183b3',
 'Torino-Stats': '105360fe',
 'Reims-Stats': '7fdd64e0',
 'West-Ham-United-Stats': '7c21e445',
 'Rennes-Stats': 'b3072e00',
 'Genoa-Stats': '658bf2de',
 'Crystal-Palace-Stats': '47c64c55',
 'Valencia-Stats': 'dcc91a7b',
 'Toulouse-Stats': '3f8c4b5f',
 'Brighton-and-Hove-Albion-Stats': 'd07537b9',
 'Bournemouth-Stats': '4ba7cbea',
 'Heidenheim-Stats': '18d9d2a7',
 'Fulham-Stats': 'fd962109',
 'Montpellier-Stats': '281b0e73',
 'Alaves-Stats': '8d6fd021',
 'Wolverhampton-Wanderers-Stats': '8cec06e1',
 'Osasuna-Stats': '03c57e2b',
 'Monza-Stats': '21680aa4',
 'Strasbourg-Stats': 'c0d3eab4',
 'Getafe-Stats': '7848bd64',
 'Everton-Stats': 'd3fd31cc',
 'Sevilla-Stats': 'ad2be733',
 'Celta-Vigo-Stats': 'f25da7fb',
 'Mallorca-Stats': '2aa12281',
 'Las-Palmas-Stats': '0049d422',
 'Brentford-Stats': 'cd051869',
 'Hellas-Verona-Stats': '0e72edf2',
 'Rayo-Vallecano-Stats': '98e8af82',
 'Lecce-Stats': 'ffcbe334',
 'Udinese-Stats': '04eea015',
 'Nantes-Stats': 'd7a486cd',
 'Empoli-Stats': 'a3d88bd8',
 'Cagliari-Stats': 'c4260e09',
 'Le-Havre-Stats': '5c2737db',
 'Frosinone-Stats': '6a7ad59d',
 'Cadiz-Stats': 'ee7c297c',
 'Metz-Stats': 'f83960ae',
 'Lorient-Stats': 'd2c87802',
 'Nottingham-Forest-Stats': 'e4a775cb',
 'Sassuolo-Stats': 'e2befd26',
 'Koln-Stats': 'bc357bf7',
 'Clermont-Foot-Stats': 'd9676424',
 'Luton-Town-Stats': 'e297cd13',
 'Burnley-Stats': '943e8050',
 'Almeria-Stats': '78ecf4bb',
 'Granada-Stats': 'a0435291',
 'Darmstadt-98-Stats': '6a6967fc',
 'Salernitana-Stats': 'c5577084',
 'Sheffield-United-Stats': '1df6b87e',
 'Eintracht-Frankfurt-Stats': 'f0ac8ee6',
 'Hoffenheim-Stats': '033ea6b8',
 'Werder-Bremen-Stats': '62add3bf',
 'Freiburg-Stats': 'a486e511',
 'Augsburg-Stats': '0cdc4311',
 'Wolfsburg-Stats': '4eaa11d7',
 'Mainz-05-Stats': 'a224b06a',
 'Monchengladbach-Stats': '32f3ee20',
 'Union-Berlin-Stats': '7a41008f',
 'Bochum-Stats': 'b42c6323'}

In [28]:
data_dict = {}
for key, value in codes_teams.items():
    url = 'https://fbref.com/en/squads/' + value + '/2023-2024/all_comps/' + key + '-All-Competitions'
    data = requests.get(url)
    content = pd.read_html(data.text, match = 'Standard Stats')
    data_dict[key] = content
    time.sleep(30)

C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')

In [118]:
df_list = []

for team in data_dict.keys():
    df = pd.DataFrame(data_dict[team][0])
    df.columns = df.columns.droplevel(0)
    print(f"Team : {team}   Col count : {len(df.columns)}")
    df['Team'] = team
    df['Team'] = df['Team'].str.rstrip('-Stats')
    df_list.append(df)

final_df = pd.concat(df_list)

final_df

Team : Bayer-Leverkusen-Stats   Col count : 34
Team : Real-Madrid-Stats   Col count : 34
Team : Internazionale-Stats   Col count : 34
Team : Manchester-City-Stats   Col count : 34
Team : Arsenal-Stats   Col count : 34
Team : Paris-Saint-Germain-Stats   Col count : 34
Team : Barcelona-Stats   Col count : 34
Team : Liverpool-Stats   Col count : 34
Team : Stuttgart-Stats   Col count : 34
Team : Girona-Stats   Col count : 34
Team : Bayern-Munich-Stats   Col count : 34
Team : Atletico-Madrid-Stats   Col count : 34
Team : Milan-Stats   Col count : 34
Team : Monaco-Stats   Col count : 34
Team : RB-Leipzig-Stats   Col count : 34
Team : Juventus-Stats   Col count : 34
Team : Dortmund-Stats   Col count : 34
Team : Atalanta-Stats   Col count : 34
Team : Athletic-Club-Stats   Col count : 34
Team : Bologna-Stats   Col count : 34
Team : Brest-Stats   Col count : 34
Team : Aston-Villa-Stats   Col count : 34
Team : Lille-Stats   Col count : 34
Team : Tottenham-Hotspur-Stats   Col count : 34
Team : Roma-Stats   Col count : 34
Team : Chelsea-Stats   Col count : 34
Team : Nice-Stats   Col count : 34
Team : Lazio-Stats   Col count : 34
Team : Newcastle-United-Stats   Col count : 34
Team : Fiorentina-Stats   Col count : 34
Team : Real-Sociedad-Stats   Col count : 34
Team : Manchester-United-Stats   Col count : 34
Team : Lyon-Stats   Col count : 34
Team : Lens-Stats   Col count : 34
Team : Real-Betis-Stats   Col count : 34
Team : Marseille-Stats   Col count : 34
Team : Napoli-Stats   Col count : 34
Team : Villarreal-Stats   Col count : 34
Team : Torino-Stats   Col count : 34
Team : Reims-Stats   Col count : 34
Team : West-Ham-United-Stats   Col count : 34
Team : Rennes-Stats   Col count : 34
Team : Genoa-Stats   Col count : 34
Team : Crystal-Palace-Stats   Col count : 34
Team : Valencia-Stats   Col count : 34
Team : Toulouse-Stats   Col count : 34
Team : Brighton-and-Hove-Albion-Stats   Col count : 34
Team : Bournemouth-Stats   Col count : 34
Team : Heidenheim-Stats   Col count : 34
Team : Fulham-Stats   Col count : 34
Team : Montpellier-Stats   Col count : 34
Team : Alaves-Stats   Col count : 34
Team : Wolverhampton-Wanderers-Stats   Col count : 34
Team : Osasuna-Stats   Col count : 34
Team : Monza-Stats   Col count : 34
Team : Strasbourg-Stats   Col count : 34
Team : Getafe-Stats   Col count : 34
Team : Everton-Stats   Col count : 34
Team : Sevilla-Stats   Col count : 34
Team : Celta-Vigo-Stats   Col count : 34
Team : Mallorca-Stats   Col count : 34
Team : Las-Palmas-Stats   Col count : 34
Team : Brentford-Stats   Col count : 34
Team : Hellas-Verona-Stats   Col count : 34
Team : Rayo-Vallecano-Stats   Col count : 34
Team : Lecce-Stats   Col count : 34
Team : Udinese-Stats   Col count : 34
Team : Nantes-Stats   Col count : 34
Team : Empoli-Stats   Col count : 34
Team : Cagliari-Stats   Col count : 34
Team : Le-Havre-Stats   Col count : 34
Team : Frosinone-Stats   Col count : 34
Team : Cadiz-Stats   Col count : 34
Team : Metz-Stats   Col count : 34
Team : Lorient-Stats   Col count : 34
Team : Nottingham-Forest-Stats   Col count : 34
Team : Sassuolo-Stats   Col count : 34
Team : Koln-Stats   Col count : 34
Team : Clermont-Foot-Stats   Col count : 34
Team : Luton-Town-Stats   Col count : 34
Team : Burnley-Stats   Col count : 34
Team : Almeria-Stats   Col count : 34
Team : Granada-Stats   Col count : 34
Team : Darmstadt-98-Stats   Col count : 34
Team : Salernitana-Stats   Col count : 34
Team : Sheffield-United-Stats   Col count : 34
Team : Eintracht-Frankfurt-Stats   Col count : 34
Team : Hoffenheim-Stats   Col count : 34
Team : Werder-Bremen-Stats   Col count : 34
Team : Freiburg-Stats   Col count : 34
Team : Augsburg-Stats   Col count : 34
Team : Wolfsburg-Stats   Col count : 34
Team : Mainz-05-Stats   Col count : 34
Team : Monchengladbach-Stats   Col count : 34
Team : Union-Berlin-Stats   Col count : 34
Team : Bochum-Stats   Col count : 34

,Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,...,G+A,G-PK,G+A-PK,xG,xAG,xG+xAG,npxG,npxG+xAG,Matches,Team
0,Granit Xhaka,ch SUI,MF,30.0,50,47,4148.0,46.1,4.0,2.0,...,0.13,0.09,0.13,0.06,0.09,0.15,0.06,0.15,Matches,Bayer-Leverkusen
1,Álex Grimaldo,es ESP,DF,27.0,51,45,4071.0,45.2,12.0,18.0,...,0.66,0.27,0.66,0.18,0.29,0.47,0.18,0.47,Matches,Bayer-Leverkusen
2,Jonathan Tah,de GER,DF,27.0,48,45,3983.0,44.3,6.0,1.0,...,0.16,0.14,0.16,0.06,0.01,0.07,0.06,0.07,Matches,Bayer-Leverkusen
3,Edmond Tapsoba,bf BFA,DF,24.0,46,39,3486.0,38.7,3.0,1.0,...,0.10,0.08,0.10,0.05,0.03,0.09,0.05,0.09,Matches,Bayer-Leverkusen
4,Florian Wirtz,de GER,"MF,FW",20.0,49,39,3456.0,38.4,18.0,19.0,...,0.96,0.42,0.91,0.34,0.30,0.64,0.32,0.62,Matches,Bayer-Leverkusen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26,Agon Elezi,mk MKD,MF,22.0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Matches,Bochum
27,Niclas Thiede,de GER,GK,24.0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Matches,Bochum
28,Moritz Römling,de GER,FW,22.0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Matches,Bochum
29,Jordi Osei-Tutu,eng ENG,"DF,MF",24.0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Matches,Bochum
30,Michael Esser,de GER,GK,35.0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Matches,Bochum

In [119]:
cols_to_keep = ['Player', 'Nation', 'Pos', 'Age', 'MP', 'Starts', 'Min', '90s', 'Gls',
       'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'Gls', 'Ast',
       'G+A', 'G-PK', 'G+A-PK', 'Matches', 'Team']
cols_to_drop = set(final_df.columns.tolist()) - set(cols_to_keep)
cols_to_drop

{'PrgC', 'PrgP', 'PrgR', 'npxG', 'npxG+xAG', 'xAG', 'xG', 'xG+xAG'}

In [120]:
final_df.to_csv('big_five_leagues_with_additional_cols.csv', index=False) # ekstra collar işe yarar mı kontrol etmek için

In [121]:
df_super_lig = pd.read_csv("player_data_super_league.csv")
cols_to_drop = [tup for tup in cols_to_drop]

big_five_revised = final_df.drop(columns=cols_to_drop, errors='ignore')
big_five_revised.columns = ['Player', 'Nation', 'Pos', 'Age', 'MP', 'Starts', 'Min', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'Gls_per_90', 'Ast_per_90', 'G+A_per_90', 'G-PK_per_90', 'G+A-PK_per_90', 'Matches','Team']

In [122]:
big_five_revised['Nation'] = big_five_revised['Nation'].str[-3:]
big_five_revised.fillna(value = 'Unknown',inplace=True)

C:\Users\deadp\AppData\Local\Temp\ipykernel_16564\3709058456.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Unknown' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  big_five_revised.fillna(value = 'Unknown',inplace=True)

In [123]:
df_all = pd.concat([df_super_lig, big_five_revised])
display(df_all)

,Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,...,PKatt,CrdY,CrdR,Gls_per_90,Ast_per_90,G+A_per_90,G-PK_per_90,G+A-PK_per_90,Matches,Team
0,Fernando Muslera,URU,GK,37.0,45,45,4019.0,44.7,0.0,0.0,...,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,Matches,Galatasaray
1,Lucas Torreira,URU,MF,27.0,43,43,3639.0,40.4,1.0,2.0,...,0.0,8.0,0.0,0.02,0.05,0.07,0.02,0.07,Matches,Galatasaray
2,Mauro Icardi,ARG,FW,30.0,42,39,3553.0,39.5,28.0,10.0,...,9.0,2.0,0.0,0.71,0.25,0.96,0.53,0.79,Matches,Galatasaray
3,Kerem Aktürkoğlu,TUR,"MF,FW",24.0,45,36,3052.0,33.9,14.0,6.0,...,4.0,5.0,1.0,0.41,0.18,0.59,0.32,0.5,Matches,Galatasaray
4,Abdülkerim Bardakcı,TUR,DF,28.0,35,32,2879.0,32.0,5.0,0.0,...,0.0,5.0,0.0,0.16,0.0,0.16,0.16,0.16,Matches,Galatasaray
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26,Agon Elezi,MKD,MF,22.0,0,0,Unknown,Unknown,Unknown,Unknown,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Matches,Bochum
27,Niclas Thiede,GER,GK,24.0,0,0,Unknown,Unknown,Unknown,Unknown,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Matches,Bochum
28,Moritz Römling,GER,FW,22.0,0,0,Unknown,Unknown,Unknown,Unknown,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Matches,Bochum
29,Jordi Osei-Tutu,ENG,"DF,MF",24.0,0,0,Unknown,Unknown,Unknown,Unknown,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Matches,Bochum
30,Michael Esser,GER,GK,35.0,0,0,Unknown,Unknown,Unknown,Unknown,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Matches,Bochum

In [127]:
df_all.to_csv('big_five_plus_super_league.csv',index=False)