In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

In [2]:
urls_with_2023 = ['https://fbref.com/en/squads/ecd11ca2/2023-2024/Galatasaray-Stats',
 'https://fbref.com/en/squads/ae1e2d7d/2023-2024/Fenerbahce-Stats',
 'https://fbref.com/en/squads/c8ad3091/2023-2024/Trabzonspor-Stats',
 'https://fbref.com/en/squads/bff39cf5/2023-2024/Istanbul-Basaksehir-Stats',
 'https://fbref.com/en/squads/d6ffefd1/2023-2024/Kasimpasa-Stats',
 'https://fbref.com/en/squads/0f9294bd/2023-2024/Besiktas-Stats',
 'https://fbref.com/en/squads/c63f6c0c/2023-2024/Sivasspor-Stats',
 'https://fbref.com/en/squads/076128d7/2023-2024/Alanyaspor-Stats',
 'https://fbref.com/en/squads/f622e63c/2023-2024/Rizespor-Stats',
 'https://fbref.com/en/squads/5ac76942/2023-2024/Antalyaspor-Stats',
 'https://fbref.com/en/squads/7c81865f/2023-2024/Gaziantep-FK-Stats',
 'https://fbref.com/en/squads/d143cf0a/2023-2024/Adana-Demirspor-Stats',
 'https://fbref.com/en/squads/77356e9e/2023-2024/Samsunspor-Stats',
 'https://fbref.com/en/squads/1f33fbc7/2023-2024/Kayserispor-Stats',
 'https://fbref.com/en/squads/4b5ddee5/2023-2024/Hatayspor-Stats',
 'https://fbref.com/en/squads/5700c020/2023-2024/Konyaspor-Stats']

urls_without_2023 = ['https://fbref.com/en/squads/b88463bd/Ankaragucu-Stats',
 'https://fbref.com/en/squads/bd61c555/Fatih-Karagumruk-Stats',
 'https://fbref.com/en/squads/2f116859/Pendikspor-Stats',
 'https://fbref.com/en/squads/6b2d5f93/Istanbulspor-Stats']
codes_teams = {}

In [3]:
split_data_with_2023 = [(url.split('/')[5], url.split('/')[7]) for url in urls_with_2023]


for code, team_name in split_data_with_2023:
    codes_teams[team_name] = code
    print(f"Code: {code}, Team Name: {team_name}")

Code: ecd11ca2, Team Name: Galatasaray-Stats
Code: ae1e2d7d, Team Name: Fenerbahce-Stats
Code: c8ad3091, Team Name: Trabzonspor-Stats
Code: bff39cf5, Team Name: Istanbul-Basaksehir-Stats
Code: d6ffefd1, Team Name: Kasimpasa-Stats
Code: 0f9294bd, Team Name: Besiktas-Stats
Code: c63f6c0c, Team Name: Sivasspor-Stats
Code: 076128d7, Team Name: Alanyaspor-Stats
Code: f622e63c, Team Name: Rizespor-Stats
Code: 5ac76942, Team Name: Antalyaspor-Stats
Code: 7c81865f, Team Name: Gaziantep-FK-Stats
Code: d143cf0a, Team Name: Adana-Demirspor-Stats
Code: 77356e9e, Team Name: Samsunspor-Stats
Code: 1f33fbc7, Team Name: Kayserispor-Stats
Code: 4b5ddee5, Team Name: Hatayspor-Stats
Code: 5700c020, Team Name: Konyaspor-Stats

In [4]:
split_data_without_2023 = [(url.split('/')[5], url.split('/')[6]) for url in urls_without_2023]

for code, team_name in split_data_without_2023:
    codes_teams[team_name] = code
    print(f"Code: {code}, Team Name: {team_name}")

Code: b88463bd, Team Name: Ankaragucu-Stats
Code: bd61c555, Team Name: Fatih-Karagumruk-Stats
Code: 2f116859, Team Name: Pendikspor-Stats
Code: 6b2d5f93, Team Name: Istanbulspor-Stats

In [5]:
data_dict = {}
for key, value in codes_teams.items():
    url = 'https://fbref.com/en/squads/' + value + '/2023-2024/all_comps/' + key + '-All-Competitions'
    data = requests.get(url)
    content = pd.read_html(data.text, match = 'Standard Stats')
    data_dict[key] = content
    time.sleep(30)

C:\Users\deadp\AppData\Local\Temp\ipykernel_2324\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_2324\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_2324\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_2324\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_2324\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_2324\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_2324\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_2324\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_2324\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_2324\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_2324\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_2324\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_2324\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_2324\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_2324\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_2324\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_2324\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_2324\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_2324\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')
C:\Users\deadp\AppData\Local\Temp\ipykernel_2324\3453854942.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  content = pd.read_html(data.text, match = 'Standard Stats')

In [46]:
df1 = pd.DataFrame(data_dict['Galatasaray-Stats'][0])
df2 = pd.DataFrame(data_dict['Konyaspor-Stats'][0])
cols_df1 = set(df1.columns)
cols_df2 = set(df2.columns)
diff = cols_df1 - cols_df2
remove = ('Unnamed: 33_level_0', 'Matches')
diff.discard(remove)
cols_to_drop = [tup[1] for tup in diff]

print(diff)

{('Expected', 'npxG+xAG'), ('Per 90 Minutes', 'npxG'), ('Per 90 Minutes', 'xAG'), ('Per 90 Minutes', 'xG'), ('Progression', 'PrgC'), ('Progression', 'PrgR'), ('Expected', 'npxG'), ('Expected', 'xAG'), ('Expected', 'xG'), ('Progression', 'PrgP'), ('Per 90 Minutes', 'xG+xAG'), ('Per 90 Minutes', 'npxG+xAG')}

In [47]:
# List to store individual DataFrames
df_list = []

# Process each key in the dictionary
for team in data_dict.keys():
    # Extract the DataFrame from the dictionary
    df = pd.DataFrame(data_dict[team][0])
    
    # Drop the first level of the MultiIndex columns
    df.columns = df.columns.droplevel(0)
    
    # Drop columns that are in cols_to_drop if they exist
    cols_to_drop_existing = [col for col in cols_to_drop if col in df.columns]
    df = df.drop(columns=cols_to_drop_existing, errors='ignore')
    
    # Check the number of columns
    print(f"{team} columns: {df.columns}")
    
    # Rename the columns if the number of columns matches the expected number
    if len(df.columns) == 22:
        df.columns = ['Player', 'Nation', 'Pos', 'Age', 'MP', 'Starts', 'Min', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'Gls_per_90', 'Ast_per_90', 'G+A_per_90', 'G-PK_per_90', 'G+A-PK_per_90', 'Matches']
    else:
        print(f"Unexpected number of columns for {team}: {len(df.columns)}")
    
    # Add a column to identify the team
    df['Team'] = team
    
    # Append the DataFrame to the list
    df_list.append(df)

# Concatenate all DataFrames into a single DataFrame
final_df = pd.concat(df_list, ignore_index=True)

# Display the final DataFrame
final_df

Galatasaray-Stats columns: Index(['Player', 'Nation', 'Pos', 'Age', 'MP', 'Starts', 'Min', '90s', 'Gls',
       'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'Gls', 'Ast',
       'G+A', 'G-PK', 'G+A-PK', 'Matches'],
      dtype='object')
Fenerbahce-Stats columns: Index(['Player', 'Nation', 'Pos', 'Age', 'MP', 'Starts', 'Min', '90s', 'Gls',
       'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'Gls', 'Ast',
       'G+A', 'G-PK', 'G+A-PK', 'Matches'],
      dtype='object')
Trabzonspor-Stats columns: Index(['Player', 'Nation', 'Pos', 'Age', 'MP', 'Starts', 'Min', '90s', 'Gls',
       'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'Gls', 'Ast',
       'G+A', 'G-PK', 'G+A-PK', 'Matches'],
      dtype='object')
Istanbul-Basaksehir-Stats columns: Index(['Player', 'Nation', 'Pos', 'Age', 'MP', 'Starts', 'Min', '90s', 'Gls',
       'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'Gls', 'Ast',
       'G+A', 'G-PK', 'G+A-PK', 'Matches'],
      dtype='object')
Kasimpasa-Stats columns: Index(['Player', 'Nation', 'Pos', 'Age', 'MP', 'Starts', 'Min', '90s', 'Gls',
       'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'Gls', 'Ast',
       'G+A', 'G-PK', 'G+A-PK', 'Matches'],
      dtype='object')
Besiktas-Stats columns: Index(['Player', 'Nation', 'Pos', 'Age', 'MP', 'Starts', 'Min', '90s', 'Gls',
       'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'Gls', 'Ast',
       'G+A', 'G-PK', 'G+A-PK', 'Matches'],
      dtype='object')
Sivasspor-Stats columns: Index(['Player', 'Nation', 'Pos', 'Age', 'MP', 'Starts', 'Min', '90s', 'Gls',
       'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'Gls', 'Ast',
       'G+A', 'G-PK', 'G+A-PK', 'Matches'],
      dtype='object')
Alanyaspor-Stats columns: Index(['Player', 'Nation', 'Pos', 'Age', 'MP', 'Starts', 'Min', '90s', 'Gls',
       'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'Gls', 'Ast',
       'G+A', 'G-PK', 'G+A-PK', 'Matches'],
      dtype='object')
Rizespor-Stats columns: Index(['Player', 'Nation', 'Pos', 'Age', 'MP', 'Starts', 'Min', '90s', 'Gls',
       'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'Gls', 'Ast',
       'G+A', 'G-PK', 'G+A-PK', 'Matches'],
      dtype='object')
Antalyaspor-Stats columns: Index(['Player', 'Nation', 'Pos', 'Age', 'MP', 'Starts', 'Min', '90s', 'Gls',
       'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'Gls', 'Ast',
       'G+A', 'G-PK', 'G+A-PK', 'Matches'],
      dtype='object')
Gaziantep-FK-Stats columns: Index(['Player', 'Nation', 'Pos', 'Age', 'MP', 'Starts', 'Min', '90s', 'Gls',
       'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'Gls', 'Ast',
       'G+A', 'G-PK', 'G+A-PK', 'Matches'],
      dtype='object')
Adana-Demirspor-Stats columns: Index(['Player', 'Nation', 'Pos', 'Age', 'MP', 'Starts', 'Min', '90s', 'Gls',
       'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'Gls', 'Ast',
       'G+A', 'G-PK', 'G+A-PK', 'Matches'],
      dtype='object')
Samsunspor-Stats columns: Index(['Player', 'Nation', 'Pos', 'Age', 'MP', 'Starts', 'Min', '90s', 'Gls',
       'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'Gls', 'Ast',
       'G+A', 'G-PK', 'G+A-PK', 'Matches'],
      dtype='object')
Kayserispor-Stats columns: Index(['Player', 'Nation', 'Pos', 'Age', 'MP', 'Starts', 'Min', '90s', 'Gls',
       'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'Gls', 'Ast',
       'G+A', 'G-PK', 'G+A-PK', 'Matches'],
      dtype='object')
Hatayspor-Stats columns: Index(['Player', 'Nation', 'Pos', 'Age', 'MP', 'Starts', 'Min', '90s', 'Gls',
       'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'Gls', 'Ast',
       'G+A', 'G-PK', 'G+A-PK', 'Matches'],
      dtype='object')
Konyaspor-Stats columns: Index(['Player', 'Nation', 'Pos', 'Age', 'MP', 'Starts', 'Min', '90s', 'Gls',
       'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'Gls', 'Ast',
       'G+A', 'G-PK', 'G+A-PK', 'Matches'],
      dtype='object')
Ankaragucu-Stats columns: Index(['Player', 'Nation', 'Pos', 'Age', 'MP', 'Starts', 'Min', '90s', 'Gls',
       'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'Gls', 'Ast',
       'G+A', 'G-PK', 'G+A-PK', 'Matches'],
      dtype='object')
Fatih-Karagumruk-Stats columns: Index(['Player', 'Nation', 'Pos', 'Age', 'MP', 'Starts', 'Min', '90s', 'Gls',
       'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'Gls', 'Ast',
       'G+A', 'G-PK', 'G+A-PK', 'Matches'],
      dtype='object')
Pendikspor-Stats columns: Index(['Player', 'Nation', 'Pos', 'Age', 'MP', 'Starts', 'Min', '90s', 'Gls',
       'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'Gls', 'Ast',
       'G+A', 'G-PK', 'G+A-PK', 'Matches'],
      dtype='object')
Istanbulspor-Stats columns: Index(['Player', 'Nation', 'Pos', 'Age', 'MP', 'Starts', 'Min', '90s', 'Gls',
       'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'Gls', 'Ast',
       'G+A', 'G-PK', 'G+A-PK', 'Matches'],
      dtype='object')

,Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,...,PKatt,CrdY,CrdR,Gls_per_90,Ast_per_90,G+A_per_90,G-PK_per_90,G+A-PK_per_90,Matches,Team
0,Fernando Muslera,uy URU,GK,37.0,45,45,4019.0,44.7,0.0,0.0,...,0.0,4.0,0.0,0.00,0.00,0.00,0.00,0.00,Matches,Galatasaray-Stats
1,Lucas Torreira,uy URU,MF,27.0,43,43,3639.0,40.4,1.0,2.0,...,0.0,8.0,0.0,0.02,0.05,0.07,0.02,0.07,Matches,Galatasaray-Stats
2,Mauro Icardi,ar ARG,FW,30.0,42,39,3553.0,39.5,28.0,10.0,...,9.0,2.0,0.0,0.71,0.25,0.96,0.53,0.79,Matches,Galatasaray-Stats
3,Kerem Aktürkoğlu,tr TUR,"MF,FW",24.0,45,36,3052.0,33.9,14.0,6.0,...,4.0,5.0,1.0,0.41,0.18,0.59,0.32,0.50,Matches,Galatasaray-Stats
4,Abdülkerim Bardakcı,tr TUR,DF,28.0,35,32,2879.0,32.0,5.0,0.0,...,0.0,5.0,0.0,0.16,0.00,0.16,0.16,0.16,Matches,Galatasaray-Stats
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
825,Enver Sarıalioğlu,NaN,MF,19.0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Matches,Istanbulspor-Stats
826,Jetmir Topalli,xk KVX,MF,25.0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Matches,Istanbulspor-Stats
827,Oktay Yakup,NaN,NaN,17.0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Matches,Istanbulspor-Stats
828,Squad Total,NaN,NaN,26.4,38,418,3420.0,38.0,28.0,18.0,...,3.0,94.0,6.0,0.74,0.47,1.21,0.71,1.18,NaN,Istanbulspor-Stats
829,Opponent Total,NaN,NaN,28.1,38,418,3420.0,38.0,78.0,55.0,...,12.0,63.0,2.0,2.05,1.45,3.50,1.82,3.26,NaN,Istanbulspor-Stats

In [48]:
final_df['Team'] = final_df['Team'].str.rstrip('-Stats')
final_df['Nation'] = final_df['Nation'].str[-3:]
final_df.fillna(value = 'Unknown', inplace = True)
final_df

C:\Users\deadp\AppData\Local\Temp\ipykernel_2324\1020427457.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Unknown' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  final_df.fillna(value = 'Unknown', inplace = True)

,Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,...,PKatt,CrdY,CrdR,Gls_per_90,Ast_per_90,G+A_per_90,G-PK_per_90,G+A-PK_per_90,Matches,Team
0,Fernando Muslera,URU,GK,37.0,45,45,4019.0,44.7,0.0,0.0,...,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,Matches,Galatasaray
1,Lucas Torreira,URU,MF,27.0,43,43,3639.0,40.4,1.0,2.0,...,0.0,8.0,0.0,0.02,0.05,0.07,0.02,0.07,Matches,Galatasaray
2,Mauro Icardi,ARG,FW,30.0,42,39,3553.0,39.5,28.0,10.0,...,9.0,2.0,0.0,0.71,0.25,0.96,0.53,0.79,Matches,Galatasaray
3,Kerem Aktürkoğlu,TUR,"MF,FW",24.0,45,36,3052.0,33.9,14.0,6.0,...,4.0,5.0,1.0,0.41,0.18,0.59,0.32,0.5,Matches,Galatasaray
4,Abdülkerim Bardakcı,TUR,DF,28.0,35,32,2879.0,32.0,5.0,0.0,...,0.0,5.0,0.0,0.16,0.0,0.16,0.16,0.16,Matches,Galatasaray
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
825,Enver Sarıalioğlu,Unknown,MF,19.0,0,0,Unknown,Unknown,Unknown,Unknown,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Matches,Istanbulspor
826,Jetmir Topalli,KVX,MF,25.0,0,0,Unknown,Unknown,Unknown,Unknown,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Matches,Istanbulspor
827,Oktay Yakup,Unknown,Unknown,17.0,0,0,Unknown,Unknown,Unknown,Unknown,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Matches,Istanbulspor
828,Squad Total,Unknown,Unknown,26.4,38,418,3420.0,38.0,28.0,18.0,...,3.0,94.0,6.0,0.74,0.47,1.21,0.71,1.18,Unknown,Istanbulspor
829,Opponent Total,Unknown,Unknown,28.1,38,418,3420.0,38.0,78.0,55.0,...,12.0,63.0,2.0,2.05,1.45,3.5,1.82,3.26,Unknown,Istanbulspor

In [49]:
final_df.to_csv('player_data_super_league.csv', index=False)